//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_GurpoA.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctr_User
    {
        public int usr_id { get; set; }
        public string usr_username { get; set; }
        public string usr_password { get; set; }
        public int usr_state { get; set; }
        public int rol_id { get; set; }
    
        public virtual Ctr_Rol Ctr_Rol { get; set; }
    }
}
