//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_GurpoA.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctr_Customer
    {
        public int ctr_id { get; set; }
        public string ctr_name { get; set; }
    }
}
