//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_GurpoA.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctr_Persona
    {
        public int per_id { get; set; }
        public string per_nombre { get; set; }
        public string per_apellido { get; set; }
        public string per_fecha_nacimiento { get; set; }
        public int per_peso { get; set; }
        public int per_altura { get; set; }
    }
}
